[BUILD] Increase jOOQ reactive timeout for testing (#2301)
* [BUILD] Increase jOOQ reactive timeout for testing

After Apache James CI issue with infra recently, the tests are somehow unstable.
PostgresBlobStoreDAOTest.concurrentSaveInputStreamShouldReturnConsistentValues:
```
18:39:45.087 [ERROR] o.a.j.b.p.u.PostgresExecutor - Time out executing Postgres query. May need to check either jOOQ reactive issue or Postgres DB performance.
java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 10000ms in 'flatMap' (and no fallback has been configured)
```

Note that the failure rate locally is really low though...

* JAMES-2586 - Override duration timeout for concurrent test in PostgresBlobStoreDAOTest

Co-authored-by: Tung Van TRAN <vttran@linagora.com>

---------

Co-authored-by: Tung Van TRAN <vttran@linagora.com>